redis:
  image: redis
  expose:
    - "6379"
  volumes:
    - data:/data
  command: redis-server --appendonly yes

nginx:
  image: klokantech/nginx
  ports:
    - "80:80"
  links:
    - embedhawk
  volumes:
    - nginx/:/etc/nginx/conf.d/
    - .htpasswd:/etc/nginx/.htpasswd

embedhawk:
  build: .
  command: /usr/local/bin/supervisord -c /etc/supervisord/supervisord.conf
  expose:
    - "5000"
  links:
    - redis
  volumes:
    - ./embed:/usr/local/src/hawk/
  environment:
    - SERVER_NAME=embedhawk.klokantech.com
    - IIIF_SERVER=http://iiifhawk.klokantech.com
    - REDIS_URL=redis://redis

ingest:
  build: ./ingest
  links:
    - redis
  volumes:
    - ./embed:/usr/local/src/hawk/
    - .boto:/etc/boto.cfg
  environment:
    - C_FORCE_ROOT=true
  command: celery --app=app.task_queue.task_queue worker -l info --workdir=/usr/local/src/hawk/
