redis:
  image: redis
  expose:
    - "6379"
  volumes:
    - data:/data
  command: redis-server --appendonly yes

embedhawk:
  build: .
  command: /usr/bin/python /usr/local/src/hawk/run_local.py
  ports:
    - "5000:5000"
  links:
    - redis
  volumes:
    - ./:/usr/local/src/hawk/

ingest:
  build: ./ingest
  links:
    - redis
  volumes:
    - ./:/usr/local/src/hawk/
    - .boto:/etc/boto.cfg
  environment:
    - C_FORCE_ROOT=true
  command: celery --app=app.task_queue.task_queue worker -l info --workdir=/usr/local/src/hawk/
