redis:
  image: redis
  expose:
    - "6379"
  volumes:
    - data:/data
  command: redis-server --appendonly yes

nginx:
  image: klokantech/nginx
  ports:
    - "80:80"
  links:
    - embed
  volumes:
    - nginx/:/etc/nginx/conf.d/
    - .htpasswd:/etc/nginx/.htpasswd

embed:
  build: ./embed
  command: /usr/local/bin/supervisord -c /etc/supervisord/supervisord.conf
  expose:
    - "5000"
  links:
    - redis
  volumes:
    - ./embed:/usr/local/src/hawk/
  environment:
    - SERVER_NAME=embedhawk.klokantech.com
    - IIIF_SERVER=http://iiifhawk.klokantech.com
    - REDIS_URL=redis://redis

ingest:
  build: ./ingest
  links:
    - redis
  volumes:
    - ./embed:/usr/local/src/hawk/
  environment:
    - C_FORCE_ROOT=true
    - REDIS_URL=redis://redis
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_ACCESS_KEY=
    - S3_CHUNK_SIZE=52428800
    - S3_HOST=s3.eu-central-1.amazonaws.com
    - S3_DEFAULT_FOLDER=jp2_bl/
    - S3_DEFAULT_BUCKET=storage.hawk.bucket
    - MAX_SUB_BATCH_REPEAT=1
    - CLOUDSEARCH_REGION=eu-central-1
    - CLOUDSEARCH_DOMAIN=embedhawk
  command: celery --app=app.task_queue.task_queue worker --workdir=/usr/local/src/hawk/
