redis:
  image: redis
  expose:
    - "6379"
  volumes:
    - data:/data
  command: redis-server --appendonly yes

embed:
  build: embed
  command: /usr/bin/python /usr/local/src/hawk/run.py
  ports:
    - "5000:5000"
  links:
    - redis
  volumes:
    - ./embed:/usr/local/src/hawk/
  environment:
    - SERVER_NAME=46fad52e.ngrok.com
    - IIIF_SERVER=http://iiifhawk.klokantech.com
    - REDIS_URL=redis://redis
    - DEBUG=True
    - HOST=0.0.0.0
    - PORT=5000

ingest:
  build: ./ingest
  links:
    - redis
  volumes:
    - ./embed:/usr/local/src/hawk/
  environment:
    - C_FORCE_ROOT=true
    - REDIS_URL=redis://redis
    - AWS_ACCESS_KEY_ID=AKIAJQHXNMLR2RIFK2GQ
    - AWS_SECRET_ACCESS_KEY=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
    - S3_CHUNK_SIZE=52428800
    - S3_HOST=s3.eu-central-1.amazonaws.com
    - S3_DEFAULT_FOLDER=jp2_bl/
    - S3_DEFAULT_BUCKET=storage.hawk.bucket
    - MAX_SUB_BATCH_REPEAT=1
    - CLOUDSEARCH_REGION=eu-central-1
    - CLOUDSEARCH_DOMAIN=embedhawk
  command: celery --app=app.task_queue.task_queue worker -E -l info --workdir=/usr/local/src/hawk/
